# Generated by Django 5.2.1 on 2025-05-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0002_todo_due_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={"ordering": ["completed", "-created_at"]},
        ),
        migrations.AlterField(
            model_name="todo",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
